### ISSUE TITLE
Dryadd crashes with unusual logging error

### ISSUE THREAD

**Issue by plesubc** [ubc-library-rc/dryad2dataverse#13]
dryadd 0.5.2; dryad2dataverse 0.6.1

On run, dryadd crashes with:

-------

Traceback (most recent call last):
  File "/home/plesack/.local/bin/dryadd", line 8, in <module>
    sys.exit(main())
  File "/home/plesack/.local/lib/python3.6/site-packages/dryad2dataverse/scripts/dryadd.py", line 528, in main
    logger = rotating_log(log, level)
  File "/home/plesack/.local/lib/python3.6/site-packages/dryad2dataverse/scripts/dryadd.py", line 452, in rotating_log
    logging.getLogger(name).setLevel(level)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1284, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib64/python3.6/logging/__init__.py", line 198, in _checkLevel
    raise TypeError("Level not an integer or a valid string: %r" % level)
TypeError: Level not an integer or a valid string: <function warning at 0x7f3514c47950>

**Comment by plesubc** [comment]
Oopsie; a bulk case change made WARNING into warning.
