### ISSUE TITLE
Dryad SMTP error

### ISSUE THREAD

**Issue by plesubc** [ubc-library-rc/dryad2dataverse#14]
(dryad2dataverse==0.5.8)

SMTP server unexpectedly closes. This may be a user issue rather than a code issue if, say, requirements have changed with the service as they often do.

```
Traceback (most recent call last):
  File "/redacted/dryadd.py", line 621, in main
    **vars(args))
  File "/redacted/dryadd.py", line 151, in notify
    server.login(kwargs['user'], kwargs['pwd'])
  File "/usr/lib64/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib64/python3.6/smtplib.py", line 631, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/lib64/python3.6/smtplib.py", line 421, in docmd
    return self.getreply()
  File "/usr/lib64/python3.6/smtplib.py", line 394, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```

**Comment by plesubc** [comment]
Appears to be a one-off; subsequent runs OK.
