### ISSUE TITLE
Emailing recipients fails with RFC 2821 non-compliance error

### ISSUE THREAD

**Issue by plesubc** [ubc-library-rc/dryad2dataverse#8]
```CRITICAL - main - Critical failure with DOI: doi:10.5061/dryad.2b906, Dryad URL: https://datadryad.org/stash/dataset/doi:10.5061/dryad.2b906, Dataverse URL: https://borealisdata.ca/dataset.xhtml?persistentId=doi:10.5683/SP2/TOBQS2
email_log - 2022-11-18 10:46:33,020 - ERROR - main - (500, b'Line length exceeded. See RFC 2821 #4.5.3.1.')
Traceback (most recent call last):
  File "/home/plesack/.local/bin/dryadd.py", line 583, in main
    recipient=args.recipients)
  File "/home/plesack/.local/bin/dryadd.py", line 126, in notify
    server.sendmail(msg['From'], msg['To'].split(','), msg.as_string())
  File "/usr/lib64/python3.6/smtplib.py", line 888, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (500, b'Line length exceeded. See RFC 2821 #4.5.3.1.')
```

In a new day of internet trivia, the maximum character length for an email paragraph is 1000 characters:

<https://www.rfc-editor.org/rfc/rfc2821#section-4.5.3.1>

```
text line
      The maximum total length of a text line including the <CRLF> is
      1000 characters (not counting the leading dot duplicated for
      transparency).  This number may be increased by the use of SMTP
      Service Extensions.
```

As some Dryad studies contain excessively long file descriptors (as per above), the paragraph length threshold is exceeded.

A repair entails splitting a dryad2dataverse.serializer.Serializer.files object and ensuring that no component is of length > 1000 before emailing.

**Comment by plesubc** [comment]
Resolved in v0.5.0.  Lengthy email messages now split with `textwrap`
